import { Link } from 'wouter';
import { ShieldCheck } from 'lucide-react';
import { useEffect, type ReactNode } from 'react';
import { PageHeader } from '../components/shared';

const policyEffectiveDate = 'September 18, 2026';

const privacyContact = 'privacy@coastwise.app';

export default function LegalPage({ kind }: { kind: 'privacy' | 'terms' }) {
  const privacy = kind === 'privacy';

  useEffect(() => {
    const previousTitle = document.title;
    const description = document.querySelector<HTMLMetaElement>('meta[name="description"]');
    const previousDescription = description?.content;
    document.title = `${privacy ? 'Privacy Policy' : 'Terms & Safety'} — Coastwise`;
    if (description) {
      description.content = privacy
        ? 'Learn how Coastwise uses camera and GPS permissions, stores family driving data locally, handles backups and sharing, and supports deletion.'
        : 'Read Coastwise terms for supervised teen driving practice, educational-use limits, guardian responsibilities, and essential safety guidance.';
    }
    return () => {
      document.title = previousTitle;
      if (description && previousDescription) description.content = previousDescription;
    };
  }, [privacy]);

  return <div className="mx-auto max-w-4xl" data-testid={privacy ? 'privacy-page' : 'terms-page'}>
    <PageHeader
      eyebrow={privacy ? 'Privacy Policy' : 'Terms & Safety'}
      title={privacy ? 'Your family’s data stays close.' : 'Practice safely. Keep an adult in charge.'}
      copy={privacy
        ? 'What Coastwise stores, when information leaves your device, and how your family can delete it.'
        : 'The limits of Coastwise’s educational guidance and the responsibilities of teen drivers and supervising adults.'}
      action={<span className="rounded-full bg-[hsl(var(--secondary))] px-3 py-2 text-xs font-bold text-[hsl(var(--primary))]">Effective {policyEffectiveDate}</span>}
    />
    <div className="rounded-2xl border border-[hsl(var(--border))] bg-[hsl(var(--card))] p-6 md:p-9">
      {privacy ? <>
        <PolicySection title="The short version">
          <p>You can use Coastwise without an account. Your profile, study progress, settings, drive logs, coaching notes, and saved drive recordings are stored in this browser on this device. We do not sell this information.</p>
          <p><strong className="text-[hsl(var(--foreground))]">Drive recordings remain device-local.</strong> They are not included in backups or uploaded by Coastwise. If that behavior changes, this policy will be updated before the new behavior is introduced.</p>
        </PolicySection>
        <PolicySection title="Optional account and family sync">
          <p>If you create an account or sign in, Coastwise’s authentication provider processes your account details, such as your email address, to sign you in. If you join a Coastwise family, profile information, study progress, goals, settings, and drive-log summaries such as date, duration, notes, and skills are sent to Coastwise’s service so approved family members can use them across devices.</p>
          <p>Drive recordings, precise routes, coaching-event positions and notes, annotations, and recording formats stay in the browser where they were created and are not included in family sync.</p>
        </PolicySection>
        <PolicySection title="Optional AI coaching">
          <p>If you choose <strong className="text-[hsl(var(--foreground))]">Generate debrief</strong>, Coastwise sends a limited drive summary to its managed AI service: duration, distance, night-driving status, selected skills, coach-event titles and descriptions, and up to three low-mastery study topics. The service uses that summary to return a coaching debrief.</p>
          <p>Coastwise does not send the drive video, family notes, profile identity, precise route, GPS coordinates, speed readings, event positions, recording metadata, or raw practice answers for an AI debrief. The returned debrief is stored inside the device-local drive review and is not included in family sync.</p>
          <p>If you choose <strong className="text-[hsl(var(--foreground))]">Create my plan</strong>, Coastwise sends up to three low-mastery topic summaries, up to three unfinished mission titles, categories, and suggested times, and up to three recent drive summaries containing duration, night-driving status, selected skills, and prior AI debrief improvement and next-step text. The service returns one skill focus, a suggested duration, and a calm parent prompt. Coastwise adds fixed safety guidance that is not generated by AI.</p>
          <p>Coastwise does not send video, precise routes, coordinates, identity, family notes, raw answers, drive dates, or recording details for a next-drive plan. The returned plan is stored locally in this browser so it remains available if the AI service is temporarily unavailable.</p>
        </PolicySection>
        <PolicySection title="Camera">
          <p>Coastwise asks for camera permission only when you choose to record a supervised drive. Coastwise does not request microphone access or record audio. The browser shows the preview and creates the video recording. You may deny permission and use other parts of Coastwise without recording.</p>
          <p>Other people who can use this device or browser profile may be able to open locally saved recordings in Coastwise.</p>
        </PolicySection>
        <PolicySection title="Location and GPS">
          <p>Coastwise asks for location permission when you build or follow a coached route. Current GPS readings support the map, route position, distance, speed estimates, and coaching cues.</p>
          <p>When you request a route, route details derived from your location are sent to Coastwise’s route service to create directions. Coastwise does not use GPS for advertising. You may deny or stop location access, but live route features will not work.</p>
        </PolicySection>
        <PolicySection title="Local storage, backups, and sharing">
          <p>Browser storage holds the student profile, permit answers, preferences, drive logs, annotations, and recordings. Clearing browser data, uninstalling the app, resetting Coastwise, or losing the device may permanently remove that information.</p>
          <p>A downloaded backup contains profile information, study progress, settings, and drive logs. It does not contain drive videos. The file leaves the device only when you download, move, or share it. A family summary or drive review is shared only when you choose a share action; the destination app or person then controls the copy you send.</p>
        </PolicySection>
        <PolicySection title="Deleting your information">
          <p>Open <Link href="/settings" className="font-bold text-[hsl(var(--primary))] underline underline-offset-4">Settings</Link> and choose <strong className="text-[hsl(var(--foreground))]">Reset local progress</strong> to delete Coastwise progress, logs, annotations, and saved drive videos from this browser. A local reset does not delete family progress already synced to Coastwise’s service. Contact us at the address below to ask about deleting cloud family data. Copies you exported or shared must also be deleted separately.</p>
        </PolicySection>
        <PolicySection title="Teens and guardians">
          <p>A parent or legal guardian should review this policy with a minor, decide whether camera and location access are appropriate, and supervise the minor’s use. Do not record passengers or bystanders without any consent required by law.</p>
        </PolicySection>
        <PolicySection title="Questions or privacy requests">
          <p>Email <a href={`mailto:${privacyContact}`} className="font-bold text-[hsl(var(--primary))] underline underline-offset-4">{privacyContact}</a>. We cannot view, recover, or delete information stored only on your device. Include no sensitive driving details in an email unless they are needed for your request.</p>
        </PolicySection>
      </> : <>
        <PolicySection title="Educational use only">
          <p>Coastwise provides study questions, practice planning, progress tracking, and general driving guidance. It is not the California DMV, a licensing authority, a driving school, a licensed driving instructor, legal advice, or a guarantee that anyone will pass a test or drive safely.</p>
          <p>The current California Driver’s Handbook, official DMV instructions, traffic laws, road signs, and directions from law enforcement take priority over Coastwise.</p>
        </PolicySection>
        <PolicySection title="The supervising adult remains responsible">
          <p>A qualified, attentive supervising adult must be present whenever the law requires supervision. That adult—not Coastwise—must decide whether the driver, vehicle, route, weather, traffic, and conditions are safe.</p>
          <p>Mount and set up the device before moving. Never read, tap, aim a camera, or troubleshoot Coastwise while driving. Pull over legally and stop if the app needs attention. Ignore any cue that is unsafe, unclear, late, or conflicts with actual conditions.</p>
        </PolicySection>
        <PolicySection title="Minors and guardian permission">
          <p>A minor may use Coastwise only with permission and oversight from a parent or legal guardian. The guardian should review permissions, local recordings, exported backups, and anything the family chooses to share. Families are responsible for following recording, privacy, learner-permit, and supervision laws.</p>
        </PolicySection>
        <PolicySection title="GPS, camera, and availability">
          <p>GPS, maps, speed estimates, route guidance, camera recording, audio, storage, and notifications may be delayed, inaccurate, interrupted, or unavailable. Coastwise is not an emergency service and must not be relied on to prevent a collision, locate a person, preserve evidence, or contact help.</p>
          <p>In an emergency, stop when safe and contact local emergency services. Do not continue a practice drive because Coastwise says a route or session is ready.</p>
        </PolicySection>
        <PolicySection title="Your content and acceptable use">
          <p>Your family is responsible for profile details, notes, recordings, backups, and shared summaries created with Coastwise. Use the app only for lawful, supervised driver education. Do not use it to secretly record people, distract a driver, violate privacy, or encourage unsafe or illegal driving.</p>
        </PolicySection>
        <PolicySection title="Changes and questions">
          <p>When material changes affect privacy, permissions, recordings, or safety responsibilities, Coastwise will update the effective date and provide updated notice in the app.</p>
          <p>Questions can be sent to <a href={`mailto:${privacyContact}`} className="font-bold text-[hsl(var(--primary))] underline underline-offset-4">{privacyContact}</a>.</p>
        </PolicySection>
      </>}
    </div>
  </div>;
}

function PolicySection({ title, children }: { title: string; children: ReactNode }) {
  return <section className="border-t border-[hsl(var(--border))] py-7 first:border-0 first:pt-0">
    <h2 className="font-display text-2xl">{title}</h2>
    <div className="mt-3 space-y-3 text-sm leading-7 text-[hsl(var(--muted-foreground))]">{children}</div>
  </section>;
}
