import { Link } from 'wouter';
import { Camera, ExternalLink, FileText, HardDrive, LockKeyhole, MapPin, ShieldCheck, Trash2 } from 'lucide-react';
import { PageHeader, SafetyNote } from '@/components/shared';

const updatedDate = 'September 17, 2026';

function LegalSection({ title, children }: { title: string; children: React.ReactNode }) {
  return <section className="rounded-2xl border border-[hsl(var(--border))] bg-[hsl(var(--card))] p-6 md:p-7"><h2 className="font-display text-2xl">{title}</h2><div className="mt-3 space-y-3 text-sm leading-6 text-[hsl(var(--muted-foreground))]">{children}</div></section>;
}

function LegalLinks() {
  return <nav className="flex flex-wrap gap-3 text-sm font-bold" aria-label="Legal pages"><Link href="/privacy" className="rounded-xl border border-[hsl(var(--border))] bg-[hsl(var(--card))] px-4 py-2.5 hover:border-[hsl(var(--primary))]">Privacy</Link><Link href="/terms" className="rounded-xl border border-[hsl(var(--border))] bg-[hsl(var(--card))] px-4 py-2.5 hover:border-[hsl(var(--primary))]">Terms & safety</Link><Link href="/settings" className="rounded-xl px-4 py-2.5 text-[hsl(var(--primary))] hover:bg-[hsl(var(--secondary))]">Settings</Link></nav>;
}

export function PrivacyPage() {
  return <div data-testid="privacy-page"><PageHeader eyebrow="Privacy" title="Your driving progress is private by default." copy={`Last updated ${updatedDate}. This notice explains what Coastwise stores, when information leaves your device, and the choices available to you.`} action={<LegalLinks />} />
    <div className="mb-6 grid gap-4 md:grid-cols-3"><div className="rounded-2xl bg-[hsl(var(--primary))] p-5 text-[hsl(var(--primary-foreground))]"><HardDrive size={20} /><div className="mt-3 text-sm font-extrabold">Local first</div><p className="mt-1 text-xs leading-5 text-white/70">Core progress works without an account and stays in this browser.</p></div><div className="rounded-2xl border border-[hsl(var(--border))] bg-[hsl(var(--card))] p-5"><LockKeyhole size={20} className="text-[hsl(var(--primary))]" /><div className="mt-3 text-sm font-extrabold">Optional family sync</div><p className="mt-1 text-xs leading-5 text-[hsl(var(--muted-foreground))]">Signing in is optional and only needed to share selected progress across devices.</p></div><div className="rounded-2xl border border-[hsl(var(--border))] bg-[hsl(var(--card))] p-5"><Camera size={20} className="text-[hsl(var(--primary))]" /><div className="mt-3 text-sm font-extrabold">Videos stay local</div><p className="mt-1 text-xs leading-5 text-[hsl(var(--muted-foreground))]">Drive recordings are not uploaded by Coastwise.</p></div></div>
    <div className="space-y-4">
      <LegalSection title="Information stored on your device"><p>Coastwise stores the student profile name, permit and target dates, handbook answers, practice history, settings, driving missions, supervised-drive logs, coaching annotations, and recorded drive videos in browser storage on the device you use.</p><p>No account is required for these features. You can download a progress backup, restore it later, or reset local progress from Settings.</p></LegalSection>
      <LegalSection title="Camera and location permissions"><p><Camera size={16} className="mr-2 inline text-[hsl(var(--primary))]" />Camera access is used only when you choose to record the road for a local drive review.</p><p><MapPin size={16} className="mr-2 inline text-[hsl(var(--primary))]" />Location access is used to build a route, show route progress, estimate speed and distance, and help return to the starting area. Location is sent to the routing service only when a route is requested.</p><p>You can deny or revoke either permission in device or browser settings. Permit practice and previously saved local content remain available without these permissions.</p></LegalSection>
      <LegalSection title="Optional accounts and family sharing"><p>If you choose family sharing, Coastwise uses an authentication provider to identify members of the family plan. Practice results, goals, settings, and drive-log summaries such as date, duration, notes, and skills may sync to Coastwise cloud storage and become visible to authorized family members.</p><p>Family sharing is optional. Precise drive routes, coaching-event positions, annotations, recording formats, and drive video files remain on the recording device and are not included in cloud sync. A parent can remove other family members from Settings.</p></LegalSection>
      <LegalSection title="Services Coastwise contacts"><p>Route requests are sent to an external routing service and may include approximate starting coordinates and generated waypoints. Optional sign-in uses Clerk authentication. Hosting and application infrastructure may process standard technical data needed to deliver requests, such as IP address, browser type, timestamps, and error logs.</p><p>Coastwise does not sell personal information or use local drive recordings for advertising.</p></LegalSection>
      <LegalSection title="Retention, backup, and deletion"><p><Trash2 size={16} className="mr-2 inline text-[hsl(var(--destructive))]" />Use “Reset local progress” to remove local progress and saved videos from the current device. Clearing browser data or uninstalling can also remove local information. Download a backup first if you want to keep progress.</p><p>Resetting a device unlinks it from sync but does not delete the family’s existing cloud progress. Signing out stops account access on that device. A family parent can remove other members. Coastwise does not currently provide self-service deletion of the shared family record, so do not enable optional sync if you require that control.</p></LegalSection>
      <LegalSection title="Teen and guardian expectations"><p>Coastwise is intended to be used with the knowledge and supervision of a parent, guardian, or other responsible adult. The supervising adult should review permissions, family access, and recording choices with the teen driver.</p></LegalSection>
      <LegalSection title="Questions"><p>For questions, contact the person or organization that provided your Coastwise access. Do not send drive videos or precise route details in a support message.</p></LegalSection>
    </div>
    <div className="mt-6"><SafetyNote /></div>
  </div>;
}

export function TermsPage() {
  return <div data-testid="terms-page"><PageHeader eyebrow="Terms & safety" title="Use Coastwise as a coach—not as the driver." copy={`Last updated ${updatedDate}. By using Coastwise, you agree to these safety and acceptable-use terms.`} action={<LegalLinks />} />
    <div className="space-y-4">
      <LegalSection title="Educational use only"><p>Coastwise provides study, planning, logging, and coaching support. It is not the California DMV, a driving school, a licensed instructor, legal advice, or a substitute for the current California Driver’s Handbook and official DMV materials.</p></LegalSection>
      <LegalSection title="Supervision and attention"><p>A permitted teen driver must follow applicable law and drive only with an eligible supervising adult. The driver must keep eyes and attention on the road. Only a passenger should operate Coastwise while the vehicle is moving.</p><p>Mount the device securely without blocking the driver’s view or vehicle controls. Do not begin or continue a coached drive when conditions, permissions, equipment, or supervision are unsafe.</p></LegalSection>
      <LegalSection title="Routes and spoken coaching"><p>Routes and instructions can be incomplete, delayed, unavailable, or wrong. Road closures, signs, traffic controls, emergency directions, and the supervising adult always take priority. Never make a sudden or illegal maneuver to follow Coastwise.</p><p>If a route fails, continue safely, pull over when appropriate, and use a trusted navigation or emergency service.</p></LegalSection>
      <LegalSection title="Recording responsibly"><p>Record only the road ahead when lawful and appropriate. Do not intentionally record private conversations, homes, faces, license plates, or other sensitive information. Follow local recording and device-mounting laws. Coastwise stores recordings locally, but anyone with access to the unlocked device may be able to view them.</p></LegalSection>
      <LegalSection title="Accounts and family access"><p>An account is not required for local coaching. If you enable optional family sharing, you are responsible for inviting only trusted people, reviewing their access, protecting sign-in methods, and removing access when it is no longer appropriate.</p></LegalSection>
      <LegalSection title="Availability and responsibility"><p>Coastwise may depend on browser storage, device sensors, internet access, and external route services. Features may not work on every device or in every location. Keep required official records separately and maintain backups of progress you need to preserve.</p></LegalSection>
      <LegalSection title="Acceptable use"><p>Do not use Coastwise to break the law, distract a driver, monitor someone without permission, upload malicious content, interfere with the service, or misrepresent practice hours or driving eligibility.</p></LegalSection>
      <LegalSection title="Changes and support"><p>These terms may be updated as Coastwise changes. The current revision date appears above. For questions, contact the person or organization that provided your Coastwise access.</p></LegalSection>
    </div>
    <div className="mt-6 flex items-start gap-3 rounded-2xl border border-[hsl(var(--primary)/.25)] bg-[hsl(var(--secondary)/.55)] p-5 text-sm leading-6"><ShieldCheck size={19} className="mt-0.5 shrink-0 text-[hsl(var(--primary))]" /><div><strong>Before every drive:</strong> confirm the vehicle is parked, the supervising adult is ready, the device is mounted, and everyone has reviewed the route and conditions.</div></div>
  </div>;
}